### ISSUE TITLE
Can't load it with ECL

### ISSUE THREAD

**Issue by catap** [usocket/trivial-sockets#1]
When I try to load `.asd` file in ECL 21.2.1 it fails with an error:
```
Error while trying to load definition for system trivial-sockets from pathname [...]/trivial-sockets.asd: keyword list is not a proper list.
```

**Comment by binghe** [comment]
Hi, this project doesn't support ECL. Please use usocket/usocket [1] instead.

[1] https://github.com/usocket/usocket
